# Builds project (with various compilers, CMake options, etc.) and runs tests
name: BasicBuilds

on: workflow_call

permissions:
  contents: read

env:
  # for installation testing - it should match with version set in CMake
  UMF_VERSION: 0.1.0

jobs:
  icx-build:
    # TODO: we could merge ICX build with gcc/clang (using our dockers) Issue: #259
    name: Intel C++ Compiler
    strategy:
      matrix:
        build_type: [Debug, Release]
        compiler: [{c: icx, cxx: icpx}]
        pool_tracking: ['ON', 'OFF']
        shared_library: ['OFF']
    env:
      BUILD_DIR : "${{github.workspace}}/build/"
      INSTL_DIR : "${{github.workspace}}/../install-dir"

    runs-on: ubuntu-22.04
    container:
      image: intel/oneapi:latest
      volumes:
        - ${{github.workspace}}:${{github.workspace}}
      options: "--privileged"

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Install apt packages
      run: |
        apt-get update
        apt-get install -y libnuma-dev libjemalloc-dev libtbb-dev libhwloc-dev python3-pip

    - name: Install Python requirements
      run: python3 -m pip install -r third_party/requirements.txt

    - name: Configure build
      run: >
        cmake
        -B build
        -DCMAKE_INSTALL_PREFIX="${{env.INSTL_DIR}}"
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DUMF_BUILD_SHARED_LIBRARY=${{matrix.shared_library}}
        -DCMAKE_C_COMPILER=${{matrix.compiler.c}}
        -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
        -DUMF_BUILD_LEVEL_ZERO_PROVIDER=ON
        -DUMF_ENABLE_POOL_TRACKING=${{matrix.pool_tracking}}
        -DUMF_FORMAT_CODE_STYLE=OFF
        -DUMF_DEVELOPER_MODE=ON
        -DUMF_BUILD_LIBUMF_POOL_JEMALLOC=ON
        -DUMF_BUILD_LIBUMF_POOL_DISJOINT=ON
        -DUMF_BUILD_LIBUMF_POOL_SCALABLE=ON
        -DUMF_BUILD_EXAMPLES=ON

    - name: Build UMF
      run: cmake --build build -j $(nproc)

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure --test-dir test

    - name: Test UMF installation and uninstallation
      # The '--shared-library' parameter is added to the installation test when the UMF is built as a shared library
      run: >
        python3 ${{github.workspace}}/test/test_installation.py
        --build-dir ${{env.BUILD_DIR}}
        --install-dir ${{env.INSTL_DIR}}
        --build-type ${{matrix.build_type}}
        --disjoint-pool
        --jemalloc-pool
        --scalable-pool
        --umf-version ${{env.UMF_VERSION}}
        ${{ matrix.shared_library == 'ON' && '--shared-library' || ''}}
