# Checks required for a PR to merge. This workflow mostly call other workflows.
name: PR/push

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  CodeCheck:
    uses: ./.github/workflows/reusable_checks.yml
  DocsBuild:
    uses: ./.github/workflows/reusable_docs_build.yml
  FastBuild:
    name: Fast builds
    needs: [CodeCheck, DocsBuild]
    uses: ./.github/workflows/reusable_fast.yml
  Build:
    name: Basic builds
    needs: [FastBuild]
    uses: ./.github/workflows/reusable_basic.yml
  DevDax:
    needs: [FastBuild]
    uses: ./.github/workflows/reusable_dax.yml
  Sanitizers:
    needs: [FastBuild]
    uses: ./.github/workflows/reusable_sanitizers.yml
  Qemu:
    needs: [FastBuild]
    uses: ./.github/workflows/reusable_qemu.yml
  Benchmarks:
    needs: [Build]
    uses: ./.github/workflows/reusable_benchmarks.yml
  ProxyLib:
    needs: [Build]
    uses: ./.github/workflows/reusable_proxy_lib.yml
  GPU:
    needs: [Build]
    uses: ./.github/workflows/reusable_gpu.yml
  Valgrind:
    needs: [Build]
    uses: ./.github/workflows/reusable_valgrind.yml
  MultiNuma:
    needs: [Build]
    uses: ./.github/workflows/reusable_multi_numa.yml
