# Run checks required for a PR to merge and verify if post-merge commit is valid.
# This workflow only call other workflows.
name: PR/push

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  CodeChecks:
    uses: ./.github/workflows/reusable_checks.yml
  DocsBuild:
    uses: ./.github/workflows/reusable_docs_build.yml
  MultiNuma:
    uses: ./.github/workflows/reusable_multi_numa.yml
  L0:
    uses: ./.github/workflows/reusable_gpu.yml
    with:
      name: "LEVEL_ZERO"
      os: "['Ubuntu', 'Windows']"
      shared_lib: "['ON']"
  CUDA:
    uses: ./.github/workflows/reusable_gpu.yml
    with:
      name: "CUDA"
      os: "['Ubuntu']"
      shared_lib: "['ON']"
  QEMU:
    uses: ./.github/workflows/reusable_qemu.yml
    with:
      short_run: true
  QEMU-long:
    uses: ./.github/workflows/reusable_qemu.yml
    with:
      short_run: false
      os: "['ubuntu-23.04', 'ubuntu-24.04']"
