# Builds project (with various compilers, CMake options, etc.) and runs tests
name: BasicBuilds

on: workflow_call

permissions:
  contents: read

env:
  BUILD_DIR : "${{github.workspace}}/build"
  INSTL_DIR : "${{github.workspace}}/../install-dir"
  COVERAGE_DIR : "${{github.workspace}}/coverage"
  COVERAGE_NAME : "exports-coverage-basic"

jobs:
  ubuntu-build:
    if: false
    name: Ubuntu
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04']
        build_type: [Release]
        compiler: [{c: gcc, cxx: g++}, ]
        shared_library: ['OFF', 'ON']
        level_zero_provider: ['OFF']
        cuda_provider: ['OFF']
        install_tbb: ['ON']
        link_hwloc_statically: ['ON']
        include:
          # test icx compiler
          - os: 'ubuntu-22.04'
            build_type: Release
            compiler: {c: icx, cxx: icpx}
            shared_library: 'ON'
            level_zero_provider: 'ON'
            cuda_provider: 'ON'
            install_tbb: 'ON'
            disable_hwloc: 'OFF'
            link_hwloc_statically: 'ON'
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0

    - name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake libnuma-dev lcov libtbb-dev

    - name: Install oneAPI basekit
      if: matrix.compiler.cxx == 'icpx'
      run: |
        sudo apt-get install -y gpg-agent wget
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
        sudo apt-get install -y intel-oneapi-ippcp-devel intel-oneapi-ipp-devel intel-oneapi-common-oneapi-vars intel-oneapi-compiler-dpcpp-cpp

    - name: Get UMF version
      run: |
        VERSION=$(git describe --tags --abbrev=0 | grep -oP '\d+\.\d+\.\d+')
        echo "UMF_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Configure build
      run: >
        ${{ matrix.compiler.cxx == 'icpx' && '. /opt/intel/oneapi/setvars.sh &&' || ''}} 
        cmake
        -B ${{env.BUILD_DIR}}
        -G "Unix Makefiles"
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DUMF_BUILD_SHARED_LIBRARY=${{matrix.shared_library}}
        -DCMAKE_C_COMPILER=${{matrix.compiler.c}}
        -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
        -DUMF_BUILD_LEVEL_ZERO_PROVIDER=${{matrix.level_zero_provider}}
        -DUMF_BUILD_CUDA_PROVIDER=${{matrix.cuda_provider}}
        -DUMF_FORMAT_CODE_STYLE=OFF
        -DUMF_DEVELOPER_MODE=OFF
        -DUMF_BUILD_LIBUMF_POOL_JEMALLOC=OFF
        -DUMF_LINK_HWLOC_STATICALLY=${{matrix.link_hwloc_statically}}

    - name: Build UMF
      run: |
        ${{ matrix.compiler.cxx == 'icpx' && '. /opt/intel/oneapi/setvars.sh' || true }}
        cmake --build ${{env.BUILD_DIR}} -j $(nproc)

  windows-build:
    name: Windows
    env:
      VCPKG_PATH: "${{github.workspace}}/build/vcpkg/packages/hwloc_x64-windows;${{github.workspace}}/build/vcpkg/packages/tbb_x64-windows;${{github.workspace}}/build/vcpkg/packages/jemalloc_x64-windows"
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2019', 'windows-2022']
        build_type: [Release]
        compiler: [{c: gcc, cxx: gcc}] # {c: clang-cl, cxx: clang-cl}, 
        shared_library: ['ON', 'OFF']
        level_zero_provider: ['OFF']
        cuda_provider: ['OFF']
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0

    - name: Initialize vcpkg
      uses: lukka/run-vcpkg@5e0cab206a5ea620130caf672fce3e4a6b5666a1 # v11.5
      with:
        vcpkgGitCommitId: 3dd44b931481d7a8e9ba412621fa810232b66289
        vcpkgDirectory: ${{env.BUILD_DIR}}/vcpkg
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Install dependencies
      run: vcpkg install
      shell: pwsh # Specifies PowerShell as the shell for running the script.

    - name: Configure MSVC environment
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

    # choco install make
    # echo "$PATH;C:\ProgramData\chocolatey\lib\make" >> $GITHUB_PATH
    # Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    - name: Install deps
      run: |
        choco install mingw

    - name: Download icx compiler
      if: false
      env:
        # Link source: https://www.intel.com/content/www/us/en/developer/tools/oneapi/dpc-compiler-download.html
        CMPLR_LINK: "https://registrationcenter-download.intel.com/akdlm/IRC_NAS/15a35578-2f9a-4f39-804b-3906e0a5f8fc/w_dpcpp-cpp-compiler_p_2024.2.1.83_offline.exe"
      run: |
        Invoke-WebRequest -Uri "${{ env.CMPLR_LINK }}" -OutFile compiler_install.exe

    - name: Install icx compiler
      if: false
      shell: cmd
      run: |
        start /b /wait .\compiler_install.exe -s -x -f extracted --log extract.log
        extracted\bootstrapper.exe -s --action install --eula=accept -p=NEED_VS2017_INTEGRATION=0 ^
          -p=NEED_VS2019_INTEGRATION=0 -p=NEED_VS2022_INTEGRATION=0 --log-dir=.

    - name: Get UMF version
      shell: pwsh
      run: |
        $version = (git describe --tags --abbrev=0 | Select-String -Pattern '\d+\.\d+\.\d+').Matches.Value
        echo "UMF_VERSION=$version" >> $env:GITHUB_ENV

      # call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
      # call "C:\Program Files (x86)\Intel\oneAPI\setvars-vcvarsall.bat"
    - name: Configure build
      shell: cmd
      run: |
        cmake ^
          -B ${{env.BUILD_DIR}} ^
          -G "Unix Makefiles" ^
          -DCMAKE_PREFIX_PATH="${{env.VCPKG_PATH}}" ^
          -DCMAKE_C_COMPILER=${{matrix.compiler.c}} ^
          -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}} ^
          -DUMF_BUILD_SHARED_LIBRARY=${{matrix.shared_library}} ^
          -DUMF_LINK_HWLOC_STATICALLY=ON ^
          -DUMF_FORMAT_CODE_STYLE=OFF ^
          -DUMF_DEVELOPER_MODE=OFF ^
          -DUMF_BUILD_LIBUMF_POOL_JEMALLOC=OFF ^
          -DUMF_BUILD_LEVEL_ZERO_PROVIDER=${{matrix.level_zero_provider}} ^
          -DUMF_BUILD_CUDA_PROVIDER=${{matrix.cuda_provider}} ^
          -DUMF_BUILD_TESTS=OFF

      # -DCMAKE_C_COMPILER_WORKS=1
      # -DCMAKE_CXX_COMPILER_WORKS=1
    - name: Build UMF
      working-directory: ${{env.BUILD_DIR}}
      shell: cmd
      run: make -j 4

    - name: Run tests
      working-directory: ${{env.BUILD_DIR}}
      run: ctest -C ${{matrix.build_type}} --output-on-failure --test-dir test
