# Basic checks on the code, incl. coding style, spelling, bandit analysis.
# TODO: add license check
name: Basic checks

on: workflow_call

permissions:
  contents: read

jobs:
  CodeChecks:
    name: Basic code checks
    runs-on: ${{ github.repository_owner == 'oneapi-src' && 'intel-ubuntu-22.04' || 'ubuntu-latest' }}
    outputs:
      filters: ${{ steps.result.outputs.result }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0

    - name: Set output
      id: result
      uses: actions/github-script@v7
      with:
        script: |
          console.log("Number of files changed:");
          return ["llvm", "llvm_spirv", "clang", "sycl_jit", "xptifw", "libclc", "sycl", "ci", "esimd"];

    - run: echo '${{ steps.result.outputs.result }}'
